apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
  labels:
    app: nodeapp-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp-kubernetes
  template:
    metadata:
      labels:
        app: nodeapp-kubernetes
    spec:
      containers:
      - name: nodeapp-kubernetes-container
        image: eldadmwangi/kubernetes_deployment:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2000
