apiVersion: v1
kind: Service
metadata:
  name: kubernetes-deployment-service
  labels:
    app: nodeapp-kubernetes
spec:
  type: LoadBalancer  # Use LoadBalancer for external access (e.g., cloud environment), or NodePort for local clusters like Minikube
  selector:
    app: nodeapp-kubernetes  # Matches the label of the pods
  ports:
    - protocol: TCP
      port: 80               # External port to expose
      targetPort: 2000       # Port on the container
      