apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend-container
          image: gcr.io/optimal-waters-446108-c1/backend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi" # Minimum memory requested
              cpu: "250m"     # Minimum CPU requested
            limits:
              memory: "256Mi" # Maximum memory allowed
              cpu: "500m"     # Maximum CPU allowed
      imagePullSecrets:
        - name: gcr-secret    # add imagepullSecretss // this is the gcr kuberneters secret
