apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  labels:
    app: node-backend
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 80          # External port exposed by the Service
      targetPort: 8080  # Port used by the container
  type: LoadBalancer
